package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.AuthorMybatis;
import org.mybatis.cdi.Mapper;

@Mapper
public interface AuthorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AUTHOR
     *
     * @mbg.generated Wed Mar 20 10:51:45 EET 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AUTHOR
     *
     * @mbg.generated Wed Mar 20 10:51:45 EET 2024
     */
    int insert(AuthorMybatis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AUTHOR
     *
     * @mbg.generated Wed Mar 20 10:51:45 EET 2024
     */
    AuthorMybatis selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AUTHOR
     *
     * @mbg.generated Wed Mar 20 10:51:45 EET 2024
     */
    List<AuthorMybatis> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AUTHOR
     *
     * @mbg.generated Wed Mar 20 10:51:45 EET 2024
     */
    int updateByPrimaryKey(AuthorMybatis record);
}
